=== yasuaki-kumazaki/teamagochi/web_backend/src/main/resources/jsonschema/events/Registration.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Registration",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "endpoint": {
      "type": "string"
    },
    "registrationId": {
      "type": "string"
    },
    "registrationDate": {
      "type": "integer",
      "format": "date-time"
    },
    "lastUpdate": {
      "type": "integer",
      "format": "date-time"
    },
    "address": {
      "type": "string"
    },
    "lwM2mVersion": {
      "type": "string"
    },
    "lifetime": {
      "type": "integer"
    },
    "bindingMode": {
      "type": "string"
    },
    "rootPath": {
      "type": "string"
    },
    "objectLinks": {
      "type": "array",
      "items": {
        "$ref": "../common/ObjectLink.json"
      }
    },
    "secure": {
      "type": "boolean"
    },
    "additionalRegistrationAttributes": {
      "$ref": "../common/AdditionalAttributes.json"
    },
    "queuemode": {
      "type": "boolean"
    },
    "availableInstances": {
      "$ref": "../common/AvailableInstances.json"
    },
    "sleeping": {
      "type": "boolean"
    },
    "smsNumber": {
      "type": "string"
    }
  },
  "required": [
    "additionalRegistrationAttributes",
    "address",
    "availableInstances",
    "bindingMode",
    "endpoint",
    "lastUpdate",
    "lifetime",
    "lwM2mVersion",
    "objectLinks",
    "queuemode",
    "registrationDate",
    "registrationId",
    "rootPath",
    "secure"
  ]
}

=== yasuaki-kumazaki/teamagochi/web_backend/src/test/resources/fixtures/json/Registration.json
{
  "endpoint": "my_device",
  "registrationId": "Hq5sYb6YE3",
  "registrationDate": 1715613881744,
  "lastUpdate": 1715613881744,
  "address": "154.43.164.20:22699",
  "lwM2mVersion": "1.0",
  "lifetime": 600,
  "bindingMode": "U",
  "rootPath": "/",
  "objectLinks": [
    {
      "url": "/1/0",
      "attributes": {}
    },
    {
      "url": "/3/0",
      "attributes": {}
    },
    {
      "url": "/4",
      "attributes": {
        "ver": "1.2"
      }
    },
    {
      "url": "/4/0",
      "attributes": {}
    },
    {
      "url": "/5/0",
      "attributes": {}
    },
    {
      "url": "/9/0",
      "attributes": {}
    },
    {
      "url": "/25",
      "attributes": {
        "ver": "2.0"
      }
    },
    {
      "url": "/27038/0",
      "attributes": {}
    },
    {
      "url": "/27039/0",
      "attributes": {}
    }
  ],
  "secure": false,
  "additionalRegistrationAttributes": {},
  "queuemode": false,
  "availableInstances": {
    "1": [
      0
    ],
    "3": [
      0
    ],
    "4": [
      0
    ],
    "5": [
      0
    ],
    "9": [
      0
    ],
    "27038": [
      0
    ],
    "27039": [
      0
    ]
  }
}
